import random

frases_otaku = {
    1: "Dattebayo!",
    2: "Nani?!",
    3: "Baka!",
    4: "Yare yare daze.",
    5: "Omae wa mou shindeiru.",
    6: "Nandayo kore?!",
    7: "Kawaii desu ne.",
    8: "Sugoi!",
    9: "Itadakimasu!",
    10: "Arigatou gozaimasu.",
    11: "Ohayo gozaimasu.",
    12: "Konbanwa.",
    13: "Ganbatte!",
    14: "Senpai, notice me!",
    15: "Konnichiwa.",
    16: "Onii-chan!",
    17: "Nee-san!",
    18: "Shinde kure!",
    19: "Yatta!",
    20: "Kuso!",
    21: "Doushite?!",
    22: "Kimi no na wa?",
    23: "Hontou ni?",
    24: "Ore wa...",
    25: "Zettai ni makenai!",
    26: "Kaizoku ou ni ore wa naru!",
    27: "Bankai!",
    28: "Getsuga tenshou!",
    29: "Tadaima!",
    30: "Okaeri!",
    31: "Gomen nasai.",
    32: "Uso da!",
    33: "Soka...",
    34: "Chotto matte!",
    35: "Subarashii!",
    36: "Kimi wa dare?",
    37: "Kisama!",
    38: "Tasukete!",
    39: "Yamete kudasai!",
    40: "Watashi wa anata o aishiteimasu.",
    41: "Betsuni.",
    42: "Kisama wa nani o suru?!",
    43: "Mada mada dane.",
    44: "Naruto-kun!",
    45: "Sasuke!",
    46: "Shannaro!",
    47: "Hoeeee!",
    48: "Tanoshi!",
    49: "Aru yo!",
    50: "Wakatta.",
    51: "Daijoubu.",
    52: "Shikata ga nai.",
    53: "Ikuzo!",
    54: "Tensai da!",
    55: "Kamehameha!",
    56: "Kawaii koto.",
    57: "Uso tsuki!",
    58: "Kimochi warui.",
    59: "Moshi moshi?",
    60: "Nandemonai.",
    61: "Shinu ka?",
    62: "Minna, genki?",
    63: "Yabai!",
    64: "Ero manga sensei!",
    65: "Gochisousama deshita.",
    66: "Omae ga ii yo.",
    67: "Sugoku tanoshii!",
    68: "Kanzen ni boku no kachi da.",
    69: "Mou ichido!",
    70: "Dame da!",
    71: "Shitsurei shimasu.",
    72: "Jibun wo shinjiru.",
    73: "Kokoro kara kansha shimasu.",
    74: "Tsubasa wo hirogete.",
    75: "Seigi wa katsu!",
    76: "Sasuga!",
    77: "Doko da?",
    78: "Doko ni iru?!",
    79: "Hayaku!",
    80: "Koko da!",
    81: "Koi wo shiyou.",
    82: "Watashi no sekai.",
    83: "Shinpai shinaide.",
    84: "Anata wa watashi no hikari.",
    85: "Hikari to yami.",
    86: "Boku no yume.",
    87: "Kesshite akiramenai.",
    88: "Sekai wo mamoru.",
    89: "Zutto issho.",
    90: "Tatakau tame ni.",
    91: "Yoru no yami.",
    92: "Hikari wa katsu.",
    93: "Subete wa unmei.",
    94: "Tsuyoku naritai.",
    95: "Ikari ga fuete.",
    96: "Shouri wo tsukamu.",
    97: "Kore ga boku no michi.",
    98: "Tomo ni tatakau.",
    99: "Mirai no tame ni.",
    100: "Yume wo kanaeru.",
    101: "Kibou wo wasurenaide.",
    102: "Shinjitsu wo sagasu.",
    103: "Anata no tame ni.",
    104: "Zutto matte ita.",
    105: "Tsumetai sekai.",
    106: "Honto ni arigatou.",
    107: "Saigo no tatakai.",
    108: "Jinsei wa tatakai.",
    109: "Watashi no uta.",
    110: "Yami kara no koe.",
    111: "Kimi wa boku no hoshi.",
    112: "Kowakunai.",
    113: "Umi no oto.",
    114: "Yama no kaze.",
    115: "Kaze no naka de.",
    116: "Taiyou no hikari.",
    117: "Mizutamari no sekai.",
    118: "Utsukushii sekai.",
    119: "Anata wo mamoru.",
    120: "Uta no naka ni.",
    121: "Yami no naka.",
    122: "Kagayaku hoshi.",
    123: "Sore wa watashi no yume.",
    124: "Kokoro no naka ni.",
    125: "Shinjite iru.",
    126: "Anata wa watashi no yuuki.",
    127: "Umi no soko kara.",
    128: "Yami no kanata.",
    129: "Shinpi no sekai.",
    130: "Kaze ni notte.",
    131: "Sekai wa utau.",
    132: "Uta ga hibiku.",
    133: "Towa no yami.",
    134: "Kaze to umi.",
    135: "Sekai no hajimari.",
    136: "Saigo no hikari.",
    137: "Anata no koe.",
    138: "Umi no naka ni.",
    139: "Kaze wa hikaru.",
    140: "Sekai wa hikari.",
    141: "Watashi no kokoro.",
    142: "Anata no kokoro.",
    143: "Sekai no owari.",
    144: "Hajimari no uta.",
    145: "Kagayaku sekai.",
    146: "Yume no naka.",
    147: "Yami ga kieru.",
    148: "Kaze to hikari.",
    149: "Umi no mukou.",
    150: "Sekai wa boku no tame ni.",
    151: "Kokoro no hikari.",
    152: "Yami no hikari.",
    153: "Shinjitsu wa hikari.",
    154: "Towa no mirai.",
    155: "Sekai wo miru.",
    156: "Yume wo tsukuru.",
    157: "Kaze no naka.",
    158: "Hikari no naka.",
    159: "Anata no sekai.",
    160: "Sekai no mirai.",
    161: "Kore wa tatakai.",
    162: "Watashi wa mamoru.",
    163: "Hoshi ga kagayaku.",
    164: "Anata wa tsuyoi.",
    165: "Yami wa akeru.",
    166: "Shori wo tsukamu.",
    167: "Sekai wo hikaru.",
    168: "Kimi wa boku no mirai.",
    169: "Yami to hikari.",
    170: "Kibou no hoshi.",
    171: "Anata wo tsuyoku.",
    172: "Kaze wa yami wo kiru.",
    173: "Sekai wa yume.",
    174: "Shinjitsu no hikari.",
    175: "Sekai wo akeru.",
    176: "Towa no yami.",
    177: "Anata no hoshi.",
    178: "Sekai wa tsuyoi.",
    179: "Kore wa watashi no sekai.",
    180: "Sekai wa hikari.",
    181: "Yami wa kanashii.",
    182: "Hikari wa kibou.",
    183: "Sekai no owari.",
    184: "Anata no koe.",
    185: "Watashi wa yume wo miru.",
    186: "Yami no kanata.",
    187: "Anata wa watashi no sekai.",
    188: "Sekai no yami.",
    189: "Hikari wo sagasu.",
    190: "Sekai wa tsuyoku.",
    191: "Kaze wa yami wo kiru.",
    192: "Sekai wa kagayaku.",
    193: "Anata wa watashi no hikari.",
    194: "Yami wa mirai.",
    195: "Sekai wa hoshi.",
    196: "Anata no hoshi.",
    197: "Hikari no hoshi.",
    198: "Sekai wa hikari.",
    199: "Kore wa sekai no hajimari.",
    200: "Watashi wa tatakau."
}


def generate_weeb_quote():
    num = random.randint(1, 200)
    print(f'num: {num}')

    return frases_otaku[num]
